### ISSUE TITLE
adjust "Remotes" dependency of dplyr@63d4a9f5

### ISSUE THREAD

**Issue by r2evans** [imanuelcostigan/RSQLServer#144]
When I reloaded RSQLServer recently, it downgraded my current install of `dplyr` to the version [as of Jan 25](https://github.com/hadley/dplyr/commit/63d4a9f5). I don't know that I need any functionality between then and now, but frankly recompiling `dplyr` is an annoyance. Is there a chance you can remove or at least update the `Remotes:` line of `DESCRIPTION`?

BTW: I have been running versions of `dplyr` newer than that commit with no problems in RSQLServer. Is it that you know there were changes that have not been fully tested?

**Comment by imanuelcostigan** [comment]
I'm not willing to change remote reference for dplyr without making sure that the significant internal changes they are making don't break the RSQLserver backend. See for example hadley/dplyr#2492 as example. I'll be rolling forward the dplyr dependency over time so that when next version of dplyr goes on cran I can't resubmit this package to CRAN in as short a possible time frame as possible. Apologies but dplyr 0.5 broke things beyond patching so we are in this situation as a result

**Comment by r2evans** [comment]
I thought it might be something like that, thanks for the explanation.
