### ISSUE TITLE
Dependency on dplyr

### ISSUE THREAD

**Issue by renkun-ken** [imanuelcostigan/RSQLServer#163]
This package depends on a non-release version of `dplyr`, which makes it annoying to work with both `RSQLServer` and the latest release of `dplyr` (v0.7, currently). May I ask why it depends on an early branch/commit of `dplyr`? Is it possible to lighten the dependencies like other `DBI`-compliant packages such as `RMySQL` and `RSQLite`?

**Comment by imanuelcostigan** [comment]
1. This package is both a DBI and dplyr backend for SQL Server so no I can't "lighten the dependencies". Read the README
2. dplyr v0.7 came out less than 24 hours ago. So if you give me slightly more time, perhaps this package will rely on this version of dplyr.

Thanks.

**Comment by Hong-Revo** [comment]
Just to clarify what @imanuelcostigan said: RSQLServer depends on dplyr 0.7. This is the latest version of dplyr, the one that's current in the [dplyr repo](https://github.com/tidyverse/dplyr), and the one whose source code is on [CRAN](https://cran.r-project.org/package=dplyr).

However, CRAN does _not_ yet have compiled binaries for dplyr 0.7. Right now, if you're on Windows or Mac and you try to install dplyr with `install.packages`, it will ask if you want to compile the 0.7 version from source. If you say no, it will download the 0.5 binary.

This should be fixed in the next couple of days.

**Comment by renkun-ken** [comment]
Huge thanks for the quick update. I tried with the latest RSQLServer and it works with latest dplyr now.

**Comment by imanuelcostigan** [comment]
The binaries are up on at least the RStudio CRAN mirror.

**Comment by Hong-Revo** [comment]
Are you sure? I just checked cran.rstudio.com, cloud.r-project.org and cran.r-project.org (and just for good measure, cran.csiro.au). All of them still have the 0.5 binaries.

**Comment by renkun-ken** [comment]
I always install github version and it works perfect with my script.

**Comment by imanuelcostigan** [comment]
@Hong-Revo actually you are correct - also explains why the Appveyor builds are failing.

**Comment by imanuelcostigan** [comment]
Conversation in #117
