### ISSUE TITLE
Use dbBind method in DBI

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#89]
### Expected behaviour

Use `DBI::dbBind()` to bind parameter values to parameterised queries 

### Actual behaviour

Using a modified version of RJDBC's `.fillStatementParameters()`. May also improve speed of dbWriteTable (see #69)

**Comment by r2evans** [comment]
`RSQLite` is using one of three templates for parameters to be used with `dbBind`:

1. straight-up `?` for all, with an unnamed list of parameters;
2. numbered question marks, i.e., `?1`, `?2`, with an unnamed list of parameters; or
3. named colons: `:Id`, `:field2`.

I can't find if/where it's defined in the `DBI` "standard" which to implement. If it is just `RSQLite` going "above-and-beyond", which of the three do you plan to implement here? Is there a fourth option?

Examples:

```r
conn <- dbConnect(RSQLServer::SQLServer(), server="...", ...) # sorry for the brevity
# 1: just question marks
res <- dbSendQuery(conn, "SELECT * FROM TableName Where Id = ? and field2 > ?")
dbBind(res, list("abc", 5))
ret <- dbFetch(res)
dbClearResult(res)

# 2: numbered question marks
res <- dbSendQuery(conn, "SELECT * FROM TableName Where Id = ?2 and field2 > ?1")
# intentionally put out-of-order to demonstrate unambiguity/usefulness
dbBind(res, list(5, "abc"))
ret <- dbFetch(res)
dbClearResult(res)

# 3: colons
res <- dbSendQuery(conn, "SELECT * FROM TableName Where Id = :Id and field2 > :field2")
dbBind(res, list(Id = "abc", field2 = 5))
ret <- dbFetch(res)
dbClearResult(res)
```

**Comment by imanuelcostigan** [comment]
I think these need to be supported by the DB backend. Let me know if there are other supported ways of specifying parameter placeholders for SQL Server.

**Comment by r2evans** [comment]
I'm afraid I won't be of much help on this. I've been searching for the last 30 minutes and can only find jTDS examples using the unnumbered `?` method. That doesn't necessarily mean that it doesn't exist, but the ["jTDS Features"](http://jtds.sourceforge.net/features.html) page specifically references "Named parameters" as supported. (I'm not certain if this pertains to parameterized queries or stored procedures.)
References: 
- http://jtds.sourceforge.net/doc/
- http://www.programcreek.com/java-api-examples/index.php?source_dir=RSQLServer-master/java/jTDS1.2.8/src/main/net/sourceforge/jtds/jdbc/ParamInfo.java

**Comment by imanuelcostigan** [comment]
Looks like named parameters are not supported by JDBC: http://stackoverflow.com/a/2309984/1193481 and https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#prepareStatement(java.lang.String)

jTDS feature list implies support for named parameters, but API docs do not confirm this.

**Comment by r2evans** [comment]
To make it even more fun ... `RPostgres` uses [dollar-num (`$1`) notation](https://github.com/rstats-db/RPostgres/issues/72), and `RSQLite` uses simple dollar (`?`), dollar-num (`?1`), and [colon-name (`:name`)](https://github.com/rstats-db/RSQLite/blob/master/R/query.R#L44). I hope rstats-db is planning standardization among their three primary (open-source) platforms.

**Comment by imanuelcostigan** [comment]
Closed by a348c8e

**Comment by r2evans** [comment]
(This topic is indirectly/very-loosely related to my params-length checking code (in #114).)

Something I do in a set of wrapper functions: named parameters (as we discussed in https://github.com/imanuelcostigan/RSQLServer/issues/89#issuecomment-242857332). My wrapper function deals with RSQLite, RPostgres, and RSQLServer, with the different mechanisms for parameters. Outside of the wrapper, I run all my queries with named parameters (`?name`).

Even though JDBC does not support anything other than positional parameters, what are your thoughts towards faking it? For instance, I can provide a PR that allows for queries such as:

```r
# one parameters referenced multiple times
dbSendQuery(conn, "SELECT * FROM TableName WHERE field1 = ?x OR field2 = ?x",
  params = list(x = 5))
# parameters not referenced
dbSendQuery(conn, "SELECT * FROM TableName WHERE field1 = ?x",
  params = list(x = 5, y = 6)
```

Both queries are legitimate, and though one might argue sloppiness when supplying more parameters than required, I suggest it can allow simpler code.

The only "gotcha" I have in this is that I use regex to find the parameters: `gregexpr("\\b\\K\\?([[:alnum:]]+)", query, perl = TRUE)`. This can (and will) fail in the face of specific (diabolical) queries. A more robust mechanism would be to use a legitimate parser to find the parameters (e.g., not within literal strings).

Is this feature strictly required? No. Is it handy? I think so. I suggest that anonymous parameters (`?`) is easy to mess up, identifying them by number is slightly better but not by much, and identifying them by name is the way queries *should* be done.

So:

1. Are you interested in this PR?
2. If yes, do you know of a way other than regex for finding parameters in the query? Getting something to work that deals well with literal strings and escaped-quotes in that string can be hairy, which is why regex is really bad at that level of parsing. (I can conceive of using a two-pass regex: one pass to identify literal strings (and not consider them), the second pass to look for parameters in all that remains. Adding complexity, sure, but identifying literal strings is actually fairly straight-forward.

**Comment by imanuelcostigan** [comment]
Thanks for your continuing great input! My strong preference is to keep the amount of hackery to a minimum and preferable only hackery of the very obvious sort. To give you some examples of some "hacks":

* The use of a `sql.yaml` file is hackery of a sort in that it fulfilled a need to work around some jTDS SSO bugs that I was experiencing. The user gets simplicity in connection back a la SSO while also keeping the workaround somewhat conspicuous. In this case it was also tapping into somewhat of an idiom 
* The introduction of the `SQLServerPreResult` and `SQLServerUpdateResult` classes were hacks to make the JDBC and DBI APIs play nice for some methods. This is an example of a hack that isn't very conspicuous and one that I'd prefer not have needed but alas...
* I did at one point hack around the inability of JDBC / SQL Server to list temp tables. That was a bad mistake and one that I ended up reversing.

**Comment by r2evans** [comment]
These are certainly understandable "hacks".

Though I confess some selfish reasons for the parameter-hack, I also suggest it aligns this package with strong recommendations *for* parameterized queries and *against* nameless/anonymous parameters. Frankly, though the three "mainstream" open-source-server drivers (RSQLite, RMysql, RPostgres) all disagree on the exact mechanism (e.g., `?abc`, `:abc`, `$abc`), I get the idea that there is an expectation of some form of named parameterization.

Doing some research, I found a more-direct (and safe) way to parse for parameters within a query: 

```r
trace("dbSendQuery", browser, exit = browser, signature=c("SQLServerConnection", "character"))
# obviously a contrived query, only two valid params; this is also a bad example
# because it mixes named and nameless, should probably trigger an warning or error
qry <- "select 1 as ABC where Field1 = ?abc AND Field2 = '?def' AND Field3 = 'what?' AND Field4 = ? ORDER BY ABC"
dbGetQuery(conn, qry)
# Browse[3]> 
md <- rJava::.jcall(pre_res@stat, "Ljava/sql/ParameterMetaData;", "getParameterMetaData")
rJava::.jcall(md, "I", "getParameterCount")
# [1] 2
(objs <- sapply(1:2, function(i) rJava::.jcall(md, "Lnet/sourceforge/jtds/jdbc/ParamInfo;", "getParameter", i)))
# [[1]]
# [1] "Java-Object{net.sourceforge.jtds.jdbc.ParamInfo@2f4d3709}"
# [[2]]
# [1] "Java-Object{net.sourceforge.jtds.jdbc.ParamInfo@4e50df2e}"
(inds <- sapply(objs, function(o) rJava::.jfield(o, "I", "markerPos")))
# [1] 31 90
(x <- substring(statement, 1 + inds, c(inds, nchar(statement))[-1]))
# [1] "?abc AND Field2 = '?def' AND Field3 = 'what?' AND Field4 = "
# [2] "? ORDER BY ABC"                                             
regmatches(x, regexpr("\\?[[:alnum:]]*", x))
# [1] "?abc" "?"   
```

This is a LOT more direct than my original statement-wide regex, giving use the specific character positions to start parsing a very straight-forward regex. It would benefit from limited parameter name length, but I can't find a formal limit on that. This has the obvious advantage of identifying parameters as JDBC sees them, so regex risk is significantly reduced (really, I think `\\?[[:alnum:]]*` is pretty bullet-proof against evil queries when you know "exactly" where the question mark starts). The only time it could fail is if a prepared statement had something like `"select 1 from abc where Field1 = ?order by abc"`, which may not even be legal.

Looking forward, JTDS does not support named parameters. And though I can find a `ParamInfo.name` field, I can't find a way to actually use it in this way, so that's stuck (perhaps only for stored procedures). In FreeTDS, of the two options for libraries, "ct-lib" [does not support parameters](http://www.freetds.org/faq.html#What.features.are.missing) (really??), and I can't find any mention of "db-lib" supporting anything other than nameless params.

If I hear you correctly, the acceptability of a "hack":

1. is inversely proportional to the risk of mis-managing an otherwise legitimate query (this includes queries that work through other languages);
2. is inversely proportional to the complexity required to get it to work; and
3. is proportional to the usefulness of the feature/function.

By using JDBC's own parameter-based methods/fields, we can significantly reduce number 1. Number 2 is subjective (though measurable with time-to-process, likely not a factor), but I think you see in the above example that translation from named to unnamed in the actual statement is now just a few lines of code away (including `regmatches<-` and `substring<-`). (The biggest detractor I can see is having to re-prepare the adjusted statement.)

This does not need to be a compatibility-breaking change: traditional nameless queries should be supported by default, and the user must intentionally enable this feature per-query. The biggest impetus for defaulting to nameless is not just "avoid the hack", but also because (for some reason) MS just does not want to support named parameters for anything other than stored procedures (ala `@name`). I hope this addresses your concern of "very obvious sort" in that it requires explicit activation by function argument.

(I confess that the largest argument *against* this is that it supports queries through this package that will not work with other SQLServer-accessing languages. Proper documentation will mitigate this a little.)
